modLoader="javafml"
loaderVersion="[37,)"
updateJSONURL="https://raw.githubusercontent.com/Exopandora/worldhandler/master/version.json"
issueTrackerURL="https://github.com/Exopandora/WorldHandler/issues"
displayURL="https://minecraft.curseforge.com/projects/world-handler-command-gui"
logoFile="logo.png"
credits="Author: Exopandora, French Translation: Koockies, Russian Translation: vanja-san, Simplified Chinese Translation: fhfuih (samhzy)"
authors="Exopandora"
logoBlur=false
license="GPL v3.0"

[[mods]]
	modId="worldhandler"
	version="1.17.1-2.12.7"
	displayName="World Handler"
	description="The World Handler provides a simple and easy to use graphical user interface for commands. It lets you create powerful and complex sub-commands alongside NBT-structures within seconds."

[[dependencies.worldhandler]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17,)"
    ordering="NONE"
    side="BOTH"